sudo: required
services:
    - docker
    
before_install:
    - docker build -t dehodgie/docker-jupyter -f Dockerfile.dev .
    - docker run -d -p 8888:8888 dehodgie/docker-jupyter

script:
    - docker ps
    - docker run -i -t dehodgie/docker-jupyter python -c 'import gdal'
    
deploy:
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "docker-jupyter"
    env: "DockerJupyter-env"
    bucket_name: "elasticbeanstalk-eu-west-2-152555717435"
    bucket_path: "docker-jupyter"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY