sudo: required
services:
    - docker
    
before_install:
    - docker build -t hodgie/Jupyter -f Dockerfile.dev . 

script:
    - docker run -e CI=true hodgie/Jupyter jupyter notebook ./data/untitled.ipynb --ip=0.0.0.0 --port=8888 --no-browser --allow-root