sudo: required
services:
    - docker
    
before_install:
    - docker build -t dehodgie/docker-jupyter -f Dockerfile.dev .
    - docker run -d -p 8888:8888 dehodgie/docker-jupyter

script:
    - docker ps
    - docker run -i -t dehodgie/docker-jupyter python -c 'import gdal'